### ISSUE TITLE
Realm: Assertion ta >= a_zero failed

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/realm#183]
I'm seeing the following assertion when I run legion applications:

```
legion_python: /home/seshu/dev/legion/runtime/realm/timers.inl:133: uint64_t Realm::Clock::TimescaleConverter::convert_forward_absolute(uint64_t): Assertion `ta >= a_zero' failed.
```

Here is a stack trace:
```
#0  0x00007fd88d0e59e5 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, 
    req=req@entry=0x55d54bf2f2e0, rem=rem@entry=0x55d54bf2f2e0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
StanfordLegion/legion#1  0x00007fd88d0ea5e7 in __GI___nanosleep (req=req@entry=0x55d54bf2f2e0, rem=rem@entry=0x55d54bf2f2e0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:25
StanfordLegion/legion#2  0x00007fd88d0ea51e in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
StanfordLegion/legion#3  0x00007fd88d71b3ed in Realm::realm_freeze (signal=6) at /home/seshu/dev/legion/runtime/realm/runtime_impl.cc:187
StanfordLegion/legion#4  <signal handler called>
StanfordLegion/legion#5  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
StanfordLegion/legion#6  0x00007fd88d09f2d3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
StanfordLegion/legion#7  0x00007fd88d04fa08 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
StanfordLegion/legion#8  0x00007fd88d038538 in __GI_abort () at abort.c:79
StanfordLegion/legion#9  0x00007fd88d03845c in __assert_fail_base (fmt=0x7fd88d1b4b08 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7fd890e1b516 "ta >= a_zero", 
    file=file@entry=0x7fd890e1b470 "/home/seshu/dev/legion/runtime/realm/timers.inl", line=line@entry=133, 
    function=function@entry=0x7fd890e1b4c8 "uint64_t Realm::Clock::TimescaleConverter::convert_forward_absolute(uint64_t)") at assert.c:92
StanfordLegion/legion#10 0x00007fd88d0483d6 in __assert_fail (assertion=0x7fd890e1b516 "ta >= a_zero", 
    file=0x7fd890e1b470 "/home/seshu/dev/legion/runtime/realm/timers.inl", line=133, 
    function=0x7fd890e1b4c8 "uint64_t Realm::Clock::TimescaleConverter::convert_forward_absolute(uint64_t)")
    at assert.c:101
StanfordLegion/legion#11 0x00007fd88ff56cae in Realm::Clock::TimescaleConverter::convert_forward_absolute (
    this=0x7fd88e71ad40 <Realm::Clock::native_to_nanoseconds>, ta=222981927203488)
    at /home/seshu/dev/legion/runtime/realm/timers.inl:133
StanfordLegion/legion#12 0x00007fd88ff56bde in Realm::Clock::current_time_in_nanoseconds (absolute=false)
    at /home/seshu/dev/legion/runtime/realm/timers.inl:67
StanfordLegion/legion#13 0x00007fd88d8a4815 in Realm::Doorbell::wait_slow (this=0x7fd88722d770)
    at /home/seshu/dev/legion/runtime/realm/mutex.cc:282
StanfordLegion/legion#14 0x00007fd88d76a845 in Realm::Doorbell::wait (this=0x7fd88722d770)
    at /home/seshu/dev/legion/runtime/realm/mutex.inl:81
StanfordLegion/legion#15 0x00007fd88d8d6d4f in Realm::ThreadedTaskScheduler::WorkCounter::wait_for_work (this=0x55d54be0c910, 
    old_counter=1) at /home/seshu/dev/legion/runtime/realm/tasks.cc:665
StanfordLegion/legion#16 0x00007fd88d8d9388 in Realm::ThreadedTaskScheduler::wait_for_work (this=0x55d54be0c750, old_work_counter=1)
    at /home/seshu/dev/legion/runtime/realm/tasks.cc:1240
StanfordLegion/legion#17 0x00007fd88d8db2e8 in Realm::UserThreadTaskScheduler::wait_for_work (this=0x55d54be0c750, old_work_counter=1)
    at /home/seshu/dev/legion/runtime/realm/tasks.cc:1741
StanfordLegion/legion#18 0x00007fd88d8d9145 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x55d54be0c750)
    at /home/seshu/dev/legion/runtime/realm/tasks.cc:1206
StanfordLegion/legion#19 0x00007fd88d8e1e48 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x55d54be0c750) at /home/seshu/dev/legion/runtime/realm/threads.inl:97
StanfordLegion/legion#20 0x00007fd88d8af6f8 in Realm::UserThread::uthread_entry () at /home/seshu/dev/legion/runtime/realm/threads.cc:1355
StanfordLegion/legion#21 0x00007fd88d0662d0 in ?? () at ../sysdeps/unix/sysv/linux/x86_64/__start_context.S:90 from /usr/lib/libc.so.6
StanfordLegion/legion#22 0x0000000000000000 in ?? ()
```

**Comment by muraj** [comment]
@syamajala I think the timer code has changed quite a bit since this issue was filed.  Can you re-verify that this is still an issue?  Thanks!
