### ISSUE TITLE
Realm: Report warning (or error) when GPU memory cannot be pinned with NIC

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/realm#194]
Some systems, notably Slingshot 11, cannot pin the full GPU's framebuffer with the NIC, especially in a 1 rank/node configuration. I have seen this on both Perlmutter and Frontier. The key signature of this failure mode is a backtrace that goes through `_gex_RMA_PutNB `. For example:

```
[6] StanfordLegion/legion#6  <signal handler called>
[6] StanfordLegion/legion#7  0x00007fb26be6d7d6 in gasnetc_rdma_put () from .../legion/language/build/lib/librealm.so.1
[6] StanfordLegion/legion#8  0x00007fb26be63ee9 in gasnete_put_nb () from .../legion/language/build/lib/librealm.so.1
[6] StanfordLegion/legion#9  0x00007fb26afc0555 in _gex_RMA_PutNB (_constantp_never_nbrhd=1, _flags=0, _lc_opt=<optimized out>, _nbytes=262144, _src=<optimized out>, _dest=<optimized out>, _rank=5, _tm=<optimized out>) at .../gasnet/release/include/ofi-conduit/gasnet_extended.h:112
[6] StanfordLegion/legion#10 Realm::XmitSrcDestPair::push_packets (this=0x7f88587a7020, immediate_mode=<optimized out>, work_until=...) at .../legion/runtime/realm/gasnetex/gasnetex_internal.cc:2416
[6] StanfordLegion/legion#11 0x00007fb26afc2ece in Realm::GASNetEXPoller::do_work (this=0x5d77720, work_until=...) at .../legion/runtime/realm/gasnetex/gasnetex_internal.cc:2944
[6] StanfordLegion/legion#12 0x00007fb26ae30fd8 in Realm::BackgroundWorkManager::Worker::do_work (this=0x7fb21c1eae20, max_time_in_ns=<optimized out>, interrupt_flag=0x0) at .../legion/runtime/realm/bgwork.cc:599
[6] StanfordLegion/legion#13 0x00007fb26ae318b1 in Realm::BackgroundWorkThread::main_loop (this=0xd5e8ed0) at .../legion/runtime/realm/bgwork.cc:103
```

The issue is that Realm does not check the return code of `gex_EP_BindSegment` (which, admittedly, was only added in GASNet-EX 2022.3.3).

The **short term** patch that I am working with to turn this into a proper error is below. Note that is NOT intended for production, as Sean wants this to be a warning by default with an optional opt-in error flag:

```diff
diff --git a/runtime/realm/gasnetex/gasnetex_internal.cc b/runtime/realm/gasnetex/gasnetex_internal.cc
index 4a7833fb5..4e3f5bb2b 100644
--- a/runtime/realm/gasnetex/gasnetex_internal.cc
+++ b/runtime/realm/gasnetex/gasnetex_internal.cc
@@ -3406,7 +3406,12 @@ namespace Realm {
     assert(ep_index == xmitsrcs.size());
     xmitsrcs.push_back(new XmitSrc(this, ep_index));

-    gex_EP_BindSegment(ep, segment, 0 /*flags*/);
+    gex_System_SetVerboseErrors(1);
+    if (gex_EP_BindSegment(ep, segment, 0 /*flags*/) != GASNET_OK) {
+      log_gex_bind.fatal() << "failed to bind segment";
+      abort();
+    }
+    gex_System_SetVerboseErrors(0);

     uintptr_t base_as_uint = reinterpret_cast<uintptr_t>(base);
     segments_by_addr.push_back({ base_as_uint, base_as_uint+size,
```

This also relies on the newer GASNet return value from `gex_EP_BindSegment` and thus is not compatible with GASNet prior to 2022.3.0. I don't know how much or if we care about that.

If we do want this to be portable to earlier versions of GASNet, a more portable solution might look something like:

```diff
--- a/runtime/realm/gasnetex/gasnetex_internal.cc
+++ b/runtime/realm/gasnetex/gasnetex_internal.cc
@@ -3407,6 +3407,8 @@ namespace Realm {
     xmitsrcs.push_back(new XmitSrc(this, ep_index));

     gex_EP_BindSegment(ep, segment, 0 /*flags*/);
+    // check for possible failure of gex_EP_BindSegment():
+    assert(gex_EP_QuerySegment(ep) == segment);

     uintptr_t base_as_uint = reinterpret_cast<uintptr_t>(base);
     segments_by_addr.push_back({ base_as_uint, base_as_uint+size,
```

Again, adjusting for Realm code style and desired error behavior.

Note that, in either case, the patches above just turn this into a proper error. Therefore, if you want to actually work around the issue, you must do one of:

 1. Reduce the amount of memory you're attempting to pin (e.g., via `-ll:fsize`)
 2. Increase the number ranks per node (e.g., from 1 to 2 is sufficient to make my use case work on Frontier)

This appears to be responsible for one major class of issues in https://github.com/StanfordLegion/gasnet/issues/27

**Comment by muraj** [comment]
We can follow up on a downgrade to a warning, etc via other feature requests about logging and such.  Closing this one as the necessary work is complete.
