### ISSUE TITLE
Crash in Realm::PosixAIORead::check_completion in resilience test

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/realm#196]
This is attempting to replicate a failure I've seen in the resilience CI, e.g. here: https://github.com/StanfordLegion/resilience/actions/runs/10647296358/job/29515103267

Failure mode:

```
StanfordLegion/legion#7  0x00007fc576f805be in Realm::PosixAIORead::check_completion (this=0x7fc4f80380b0)
    at /scratch/eslaught/resilience-test-network/legion/runtime/realm/transfer/lowlevel_dma.cc:350
StanfordLegion/legion#8  0x00007fc576f8124d in Realm::AsyncFileIOContext::do_work (this=0x556822bed5a0, work_until=...)
    at /scratch/eslaught/resilience-test-network/legion/runtime/realm/transfer/lowlevel_dma.cc:604
StanfordLegion/legion#9  0x00007fc57716be8e in Realm::BackgroundWorkManager::Worker::do_work (this=0x7fc56aeb39c0, max_time_in_ns=-1, 
    interrupt_flag=0x0) at /scratch/eslaught/resilience-test-network/legion/runtime/realm/bgwork.cc:599
StanfordLegion/legion#10 0x00007fc577169844 in Realm::BackgroundWorkThread::main_loop (this=0x556822be97c0)
    at /scratch/eslaught/resilience-test-network/legion/runtime/realm/bgwork.cc:103
StanfordLegion/legion#11 0x00007fc57716d324 in Realm::Thread::thread_entry_wrapper<Realm::BackgroundWorkThread, &Realm::BackgroundWorkThread::main_loop> (obj=0x556822be97c0) at /scratch/eslaught/resilience-test-network/legion/runtime/realm/threads.inl:97
```

Note the failure mode isn't the same as what I saw in CI, but this is the best I can do for now. It's possible that if we resolved this issue we'd see the other failure mode return afterwards.

Note I'm going to share the build with StanfordLegion/legion#1752, so watch out when you rebuild it:

To reproduce:

```
cd /scratch/eslaught/resilience-test-network
source experiment/sapling/env.sh
cd test_region
salloc -n 1 -N 1 -c 40 -p all --exclusive
for i in $(seq 0 40); do ./test.sh "test_$i" & done
```

Reproduction ratio seems to be about 10%.

To rebuild:

```
cd /scratch/eslaught/resilience-test-network
source experiment/sapling/env.sh
srun -n 1 -N 1 -c 40 -p all --exclusive --pty bash --login
./experiment/setup.sh
```

**Comment by muraj** [comment]
@elliottslaughter can we get an update on this when you get a chance?  I think Mike is asking for a Legion Spy log to verify this isn't an issue with either app or legion teardown / reinitialization?
